/** Chaves alinhadas ao menu comercial (filtro do sidebar). */
export type DashboardMenuKey =
  | 'dashboard'
  | 'produtos'
  | 'pedidos'
  | 'entregadores'
  | 'caixa'
  | 'configuracoes'
  | 'assinatura'
  | 'promocoes'
  | 'relatorios'
  | 'aparencia'
  | 'impressao'
  | 'balanca'
  | 'kds'
  | 'pdv'
  | 'garcom'
  | 'garcons'
  | 'automacoes'
  | 'fiscal'
  | 'master_whatsapp'
  | 'master_fidelidade'
  | 'master_marketing'
  | 'master_hub'
